apiVersion: v1
kind: Service 
metadata:
  name: frontend
  namespace: llm-as-a-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80  # The port other services use to reach this service
      targetPort: 80  # The port on the backend container
  type: ClusterIP  # Internal service, only accessible within the cluster